// Script de peuplement de la base avec des données de démo
// correspondant aux profils "mock" déjà présents dans le frontend
// (TechFlow AI, Sophie Chen, TechAngels, Jack Ma...).
// Usage: npm run seed
require("dotenv").config();
const connectDB = require("../config/db");
const User = require("../models/User");

const demoUsers = [
  {
    role: "startup",
    firstName: "Ayman",
    lastName: "Ben Salah",
    email: "contact@techflow.ai",
    password: "Password1",
    company: "TechFlow AI",
    location: "Paris",
    link: "https://techflow.ai",
    description: "Solution d'automatisation des workflows par IA générative.",
    interests: ["AI/ML", "SaaS", "Serie A"],
    stage: "Serie A",
    tagline: "Solution d'automatisation des workflows par IA générative",
    founded: "Fondée en 2023",
    size: "11-50 employés",
    tags: ["AI/ML", "SaaS", "B2B", "Automatisation"],
    accomplishments: [
      { icon: "🏆", label: "Station F Batch 2023" },
      { icon: "📈", label: "€500k AAR" },
      { icon: "👥", label: "+100 clients" },
    ],
    about: [
      "TechFlow AI développe une plateforme SaaS qui utilise l'IA générative pour automatiser les workflows complexes des entreprises.",
      "Notre solution permet aux équipes de réduire de 70% le temps passé sur les tâches répétitives.",
    ],
    skills: [
      { label: "Intelligence Artificielle", value: 95 },
      { label: "Automatisation", value: 90 },
    ],
    parcours: [
      { date: "Jan 2023", title: "Création", desc: "Lancement de TechFlow AI" },
      { date: "Jan 2024", title: "Seed Round", desc: "Levée de €2M" },
    ],
  },
  {
    role: "talent",
    firstName: "Sophie",
    lastName: "Chen",
    email: "sophie.chen@example.com",
    password: "Password1",
    company: "",
    location: "Remote",
    link: "https://linkedin.com/in/sophiechen",
    description: "Senior Full-Stack Developer, 8 ans d'expérience React/Node.",
    interests: ["React", "Node.js", "TypeScript"],
    tagline: "Senior Full-Stack Developer",
  },
  {
    role: "investisseur",
    firstName: "Amine",
    lastName: "Trabelsi",
    email: "contact@techangels.vc",
    password: "Password1",
    company: "TechAngels",
    location: "Europe",
    link: "https://techangels.vc",
    description: "Business angels investissant dans l'innovation tech.",
    interests: ["Pre-seed", "Tech", "Serie A"],
    budgetRange: "10M-50M DT",
  },
  {
    role: "incubateur",
    firstName: "Jack",
    lastName: "Ma",
    email: "jack.ma@incub.example.com",
    password: "Password1",
    company: "Global Incubator",
    location: "WorldWide",
    link: "https://example.com",
    description: "Offre hébergement (bureaux, coworking), conseil et mentorat.",
    interests: ["Tech", "Finance", "Seed"],
  },

  // ── Jeu de données étendu ────────────────────────────────────────────
  // Volontairement varié en stage/budget/secteur/localisation pour pouvoir
  // observer de "bons" ET de "mauvais" matchs sur les 4 facteurs du score
  // (voir backend/src/utils/compatibility.js), pas seulement des cas idéaux.

  // Startups — un par stade de financement
  {
    role: "startup",
    firstName: "Lina",
    lastName: "Cherif",
    email: "lina@greenloop.tn",
    password: "Password1",
    company: "GreenLoop",
    location: "Tunisia",
    link: "https://greenloop.tn",
    description: "Capteurs IoT pour l'irrigation de précision en agriculture.",
    interests: ["GreenTech", "IoT"],
    stage: "Pre-seed",
    tagline: "L'irrigation intelligente pour l'agriculture tunisienne",
    tags: ["GreenTech", "IoT", "AgriTech"],
  },
  {
    role: "startup",
    firstName: "Omar",
    lastName: "Bouazizi",
    email: "omar@medisync.tn",
    password: "Password1",
    company: "MediSync",
    location: "Tunisia",
    link: "https://medisync.tn",
    description: "Plateforme de suivi de patients à distance pour cliniques.",
    interests: ["HealthTech", "SaaS"],
    stage: "Seed",
    tagline: "Le suivi patient à distance, simplifié",
    tags: ["HealthTech", "SaaS"],
  },
  {
    role: "startup",
    firstName: "Chloé",
    lastName: "Girard",
    email: "chloe@paynest.fr",
    password: "Password1",
    company: "PayNest",
    location: "France",
    link: "https://paynest.fr",
    description: "Solution de paiement fractionné pour PME.",
    interests: ["FinTech", "SaaS"],
    stage: "Serie A",
    tagline: "Le paiement fractionné pensé pour les PME",
    tags: ["FinTech", "SaaS"],
  },
  {
    role: "startup",
    firstName: "Rania",
    lastName: "Haddad",
    email: "rania@shopwave.ae",
    password: "Password1",
    company: "ShopWave",
    location: "UAE",
    link: "https://shopwave.ae",
    description: "Marketplace régionale pour artisans et créateurs indépendants.",
    interests: ["E-commerce", "Marketplace"],
    stage: "Serie B",
    tagline: "La marketplace des créateurs indépendants du Golfe",
    tags: ["E-commerce", "Marketplace"],
  },
  {
    role: "startup",
    firstName: "Yassine",
    lastName: "Kammoun",
    email: "yassine@eduspark.io",
    password: "Password1",
    company: "EduSpark",
    location: "Remote",
    link: "https://eduspark.io",
    description: "Plateforme d'apprentissage adaptatif pour lycéens.",
    interests: ["EdTech", "SaaS"],
    stage: "Croissance",
    tagline: "L'apprentissage adaptatif, à grande échelle",
    tags: ["EdTech", "SaaS"],
  },
  {
    role: "startup",
    firstName: "Nadia",
    lastName: "Ferjani",
    email: "nadia@securenet.eu",
    password: "Password1",
    company: "SecureNet",
    location: "Europe",
    link: "https://securenet.eu",
    description: "Audit de cybersécurité automatisé pour PME.",
    interests: ["Cybersecurite", "SaaS"],
    stage: "Pre-seed",
    tagline: "L'audit cybersécurité automatisé pour PME",
    tags: ["Cybersecurite", "SaaS"],
  },
  {
    role: "startup",
    firstName: "Karim",
    lastName: "Belhaj",
    email: "karim@agropulse.tn",
    password: "Password1",
    company: "AgroPulse",
    location: "MENA",
    link: "https://agropulse.tn",
    description: "Données satellites pour l'optimisation des rendements agricoles.",
    interests: ["AgriTech", "IoT"],
    stage: "Seed",
    tagline: "Des rendements agricoles optimisés par satellite",
    tags: ["AgriTech", "IoT"],
  },

  // Investisseurs — un par tranche de budget, secteurs variés
  {
    role: "investisseur",
    firstName: "Sami",
    lastName: "Gharbi",
    email: "sami@seedbridge.vc",
    password: "Password1",
    company: "SeedBridge Capital",
    location: "Tunisia",
    link: "https://seedbridge.vc",
    description: "Fonds pré-amorçage/amorçage, tickets petits mais nombreux.",
    interests: ["FinTech", "HealthTech", "AgriTech"],
    budgetRange: "0-10M DT",
  },
  {
    role: "investisseur",
    firstName: "Hela",
    lastName: "Mansour",
    email: "hela@atlasgrowth.fr",
    password: "Password1",
    company: "Atlas Growth Partners",
    location: "France",
    link: "https://atlasgrowth.fr",
    description: "Croissance post-Series A, e-commerce et SaaS B2B.",
    interests: ["E-commerce", "SaaS", "Marketplace"],
    budgetRange: "50M-100M DT",
  },
  {
    role: "investisseur",
    firstName: "Tarek",
    lastName: "Zouari",
    email: "tarek@horizonmena.ae",
    password: "Password1",
    company: "Horizon MENA Fund",
    location: "MENA",
    link: "https://horizonmena.ae",
    description: "Late-stage growth fund, tickets importants sur toute la région.",
    interests: ["GreenTech", "EdTech", "Cybersecurite"],
    budgetRange: "100M+ DT",
  },
  {
    role: "investisseur",
    firstName: "Ines",
    lastName: "Dridi",
    email: "ines@nextgen.vc",
    password: "Password1",
    company: "NextGen Ventures",
    location: "Remote",
    link: "https://nextgen.vc",
    description: "Series A généraliste, tech & IoT.",
    interests: ["SaaS", "IoT", "FinTech"],
    budgetRange: "10M-50M DT",
  },

  // Incubateurs / accompagnement
  {
    role: "incubateur",
    firstName: "Mehdi",
    lastName: "Slim",
    email: "mehdi@tunishub.tn",
    password: "Password1",
    company: "Tunis Startup Hub",
    location: "Tunisia",
    link: "https://tunishub.tn",
    description: "Incubateur généraliste basé à Tunis, mentorat + coworking.",
    interests: ["FinTech", "AgriTech", "HealthTech"],
  },
  {
    role: "incubateur",
    firstName: "Salma",
    lastName: "Ayari",
    email: "salma@menalaunch.com",
    password: "Password1",
    company: "MENA Launchpad",
    location: "MENA",
    link: "https://menalaunch.com",
    description: "Programme d'accélération régional, 3 promotions par an.",
    interests: ["E-commerce", "EdTech", "GreenTech"],
  },

  // Talents
  {
    role: "talent",
    firstName: "Yassine",
    lastName: "Karray",
    email: "yassine.karray@example.com",
    password: "Password1",
    company: "",
    location: "Tunisia",
    link: "https://linkedin.com/in/yassinekarray",
    description: "Product designer, spécialisé fintech & marketplaces.",
    interests: ["SaaS", "FinTech"],
    tagline: "Product designer — Fintech & Marketplaces",
  },
];

(async () => {
  try {
    await connectDB();
    await User.deleteMany({ email: { $in: demoUsers.map((u) => u.email) } });
    await User.create(demoUsers);
    console.log(`✅ ${demoUsers.length} utilisateurs de démo créés.`);
    process.exit(0);
  } catch (err) {
    console.error("Erreur de seed:", err);
    process.exit(1);
  }
})();
